import os

POSTGRES_USER = os.getenv("NOTIFICATION_DB_USER")
POSTGRES_PASSWORD = os.getenv("NOTIFICATION_DB_PASSWORD")
POSTGRES_DB = os.getenv("NOTIFICATION_DB_NAME")

DATABASE_URL = os.getenv("NOTIFICATION_DATABASE_URL")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT", 6379))

RABBIT_URL = os.getenv("RABBIT_URL")
