name: CI                  # Nombre del workflow
on: [push, pull_request]  # Eventos que disparan el workflow

jobs:
  test:                     # Nombre del Job
    runs-on: ubuntu-latest  # Runner (maquina virtual) donde se ejecuta el job
    steps:
      - uses: actions/checkout@v4 # Paso 1: clonar repo
      - run: echo "Hola CI!"  # Paso 2: Ejectua un comando de ejemplo