import os

DATABASE_URL = os.getenv("USER_DATABASE_URL")

REDIS_URL = os.getenv("REDIS_URL")
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))


PRIVATE_KEY = os.getenv("PRIVATE_KEY")
PUBLIC_KEY = os.getenv("PUBLIC_KEY")

ALGORITHM = "RS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30